import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { Navbar } from "./components/navbar";
import { verifyStats } from "../action/stats/verifyStats";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const now = new Date();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const year = now.getFullYear();
  await verifyStats(`${month}/${year}`);

  return (
    <html lang="es">
      <body className={`${inter.variable} antialiased overflow-x-hidden `}>
        <Navbar />
        <div className="">{children}</div>
      </body>
    </html>
  );
}
